---
- hosts: mrlokans
  become: true
  become_method: sudo

  vars:
    - project_repo: https://github.com/MrLokans/bank_telegram_bot
    - project_root_dir: /opt/telegram_bot/
    - project_virtualenv_folder: /opt/telegram_bot/venv/
    - bot_api_token: "{{  lookup('file', 'credentials')  }}"
    - bot_supervisor_owner: mrlokans

  roles:
    # - { role: telegrambot,  project_repo: "{{ project_repo }}", 
    #                         project_root_dir: "{{ project_root_dir }}", 
    #                         project_virtualenv_folder: "{{ project_virtualenv_folder}}",
    #                         bot_api_token: "{{ bot_api_token }}",
    #                         bot_supervisor_owner: "{{ bot_supervisor_owner}}"}
    - telegrambot
