  - name: Update the packages list (Debian)
    when: ansible_os_family == 'Debian'
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: (RedHat) Add mongodb repository
    sudo: yes
    template: src=rhel_mongodb.repo dest=/etc/yum.repos.d/mongodb-org-3.0.repo
    when: ansible_os_family == 'RedHat'


  - name: (Debian) Install mongodb and python library
    when: ansible_os_family == 'Debian'
    apt: name={{ item }} state=present
    with_items: 
      - mongodb-org
      - python-pymongo


  - name: (RedHat) Install mongodb and python library
    when: ansible_os_family == 'RedHat'
    yum: name={{ item }} state=latest update_cache=yes
    ignore_errors: True

    with_items: 
      - python-pymongo
      - mongodb-server
      - mongodb


  - name: Ensure mongodb is running.
    service: name=mongod state=started enabled=yes

  # - name: Set up mongoDB
  #   mongodb_user: 
  #     database="{{ mongo_db }}"
  #     name="{{ mongo_user }}"
  #     password="{{ mongo_password }}"
  #     state=present 
  #     roles=readWriteAnyDatabase
  #     login_database="{{ mongo_db }}"
  #   notify: restart mongodb
