  - name: (RedHat) Install Python and pip
    when: ansible_os_family == 'RedHat'
    yum: name={{ item }} state=latest update_cache=yes

    with_items: 
      - python34
      - python-pip
      - python34-devel 
