---
- hosts: mrlokans
  become: true
  become_method: sudo

  vars:
    - project_repo: https://github.com/MrLokans/bank_telegram_bot
    - project_root_dir: /opt/telegram_bot/
    - project_virtualenv_folder: /opt/telegram_bot/venv/
    - bot_api_token: "{{ lookup('ini', 'token section=telegram file=credentials.ini') }}"
    - bot_supervisor_owner: mrlokans

    - redis_host: "{{ lookup('ini', 'redis_host section=redis file=credentials.ini') }}"
    - redis_port: "{{ lookup('ini', 'redis_port section=redis file=credentials.ini') }}"
    - redis_db: "{{ lookup('ini', 'redis_db section=redis file=credentials.ini') }}"

  roles:
    - epel
    - python
    # - mongodb
    - supervisord
    - redis
    - telegrambot
